In [4]:
import pandas as pd
import csv

In [11]:
AISdailyaggregates = pd.DataFrame(columns=["Installation ID","aggregate_date","hours_moving","hours_not_moving","hours_uncertain","completeness","distance_moved","min_speed","max_speed","avg_draught","avg_abs_turn_rate","record_count","last_position_time","last_position_latitude","last_position_longitude","last_speed"])
with open("/Users/alexeylevakin/Documents/SeaDevCon18/enrichment/SeaDevCon_AISdailyaggregates_sanitized.csv") as file:
    reader = csv.reader(file, delimiter=';', skipinitialspace=True)
    for r in reader:
        try:
            AISdailyaggregates = AISdailyaggregates.append({
                'Installation ID': r[0],
                'aggregate_date': r[1],
                'hours_moving': r[2],
                'hours_not_moving': r[3],
                'hours_uncertain': r[4],
                'completeness': r[5],
                'distance_moved': r[6],
                'min_speed': r[7],
                'max_speed': r[8],
                'avg_draught': r[9],
                'avg_abs_turn_rate': r[10],
                'record_count': r[11],
                'last_position_time': r[12],
                'last_position_latitude': r[13],
                'last_position_longitude': r[14],
                'last_speed': r[15]
            }, ignore_index = True)
        except BaseException as e:
            print(e)

In [12]:
AISdailyaggregates.head(5)

,Installation ID,aggregate_date,hours_moving,hours_not_moving,hours_uncertain,completeness,distance_moved,min_speed,max_speed,avg_draught,avg_abs_turn_rate,record_count,last_position_time,last_position_latitude,last_position_longitude,last_speed
0,Installation ID,aggregate_date,hours_moving,hours_not_moving,hours_uncertain,completeness,distance_moved,min_speed,max_speed,avg_draught,avg_abs_turn_rate,record_count,last_position_time,last_position_latitude,last_position_longitude,last_speed
1,_00067,01.11.2015,"22,1386",0,0,"0,922442","775,991","18,02","19,36","11,2",0,9,22:28:28,"8,88695","111,532","17,7"
2,_00067,02.11.2015,24,0,0,1,"817,664","18,34","18,5","11,2",0,3,21:35:52,"14,4236","116,045","18,5"
3,_00067,03.11.2015,24,0,0,1,"760,143","15,46","17,46","11,2",0,3,12:55:00,"17,8005","118,805","15,2"
4,_00067,04.11.2015,24,0,0,1,"817,234","17,75","18,75","11,2",0,6,23:54:40,"25,1636","126,953","18,8"